name        = "Ergo-L-Sofle"
name8       = "ergolsof"
locale      = "fr"
variant     = "ergol"
description = "French (Ergo-L RDE Sofle)"
author      = "rdeneau"
url         = "https://github.com/Nuclear-Squid/ergol"
geometry    = "ERGO"
version     = "1.0.0"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ esc ┃ $   │ '   │ "   │ €   │ %   ┃ |   │ &   │ *   │ #   │ @   ┃ ins ┆     ┆
┆     ┃ f2  │ f3  │ f4  │ f5  │ f6  ┃ f8  │ f9  │ f10 │ f11 │ f12 ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Q   │ C   │ O   │ P   │ W   ┃ J   │ M   │ D   │ !   │ Y   ┃ del ┆     ┆
·     ┃   â │   ç │   œ │   ô │   § ┃   ↩ │   µ │   • │***  │   û ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ S   │ E   │ N   │ F   ┃ L   │ R   │ T   │ I   │ U   ┃ bspc┆     ┆
·     ┃   à │   é │   è │   ê │   ≠ ┃   ↔ │   → │   î │   ï │   ù ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ lsft┃ Z   │ X   │ ?   │ V   │ B   ┃ :   │ H   │ G   │ ;   │ K   ┃
┆     ┃   ñ │   ‑ │ -   │   – │   — ┃ .   │   … │  *µ │ ,   │     ┃
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
┆     ┃   ¤ │   « │   » │     │   ° ┃   ≤ │   ≥ │   × │   ± │   ÷ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *^ │   ≤ │   ≥ │  *¤ │   ‰ ┃  *˚ │     │   × │  *` │  *´ ┃     ┆     ┆
·     ┃   ^ │   < │   > │   $ │   % ┃   / │   & │   * │   ` │   ´ ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *ˇ │     │     │  *˙ │   ≠ ┃  */ │   ± │  *¯ │     │  *” ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   = ┃   \ │   + │   - │   ' │   " ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃  *~ │  *, │  *˛ │   – │     ┃     │   ¦ │  *¸ │   : │  *˘ ┃
┆     ┃   ~ │   [ │   ] │   _ │   # ┃   ! │   | │   ; │   : │   ? ┃
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚
'''

[spacebar]
shift       = "\u00a0"  # NO-BREAK SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u202f"  # NARROW NO-BREAK SPACE
