name        = "Ergo-LR-ANSI"
name8       = "ergolra"
locale      = "en"
variant     = "ergol"
description = "French (Ergo-LR, ANSI)"
author      = "rdeneau"
url         = "https://github.com/rdeneau/kalamine"
geometry    = "ANSI"
version     = "1.0.0"

# Legend for special keys:
# lmet = Windows (Left)
# lalt = Alt (Left)
# ralt = AltGr (Right)
# ***  = 1st dead key 1dk (Accents Layer)
# &&&  = 2nd dead key 2dk (NavNum Layer) (Omitted, Handled by the keyboard directly)
# ent  = Enter
# spc  = Space
# menu = Property (~ Right Click)
# lctl / rctl = Control (Left / Right)

# Base layer, including 1dk
#                +-----+
# shift -------> | ? ¿ | <----- 1dk, shift+key
# base --------> | / ÷ | <----- 1dk, key
#                +-----+
base = '''
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┲━━━━━━━━━━┓
│ esc │ $   │ '   │ "   │ €   │ %   │ |   │ &   │ *   │ #   │ @   │ ins │     ┃          ┃
│     │ f2  │ f3  │ f4  │ f5  │ f6  │ f8  │ f9  │ f10 │ f11 │ f12 │     │     ┃ ⌫        ┃
┢━━━━━┷━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┺━━┯━━━━━━━┩
┃ tab    ┃ Q   │ C   │ O   │ P   │ W   │ J   │ M   │ D   │ !   │ Y   │ del │     │       │
┃        ┃   â │   ç │   œ │   ô │   § │   ↩ │   µ │   • │***  │   û │     │     │       │
┣━━━━━━━━┻┱────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┲━━━━┷━━━━━━━┪
┃ caps    ┃ A   │ S   │ E   │ N   │ F   │ L   │ R   │ T   │ I   │ U   │ bspc┃            ┃
┃         ┃   à │   é │   è │   ê │   ≠ │   ↔ │   → │   î │   ï │   ù │     ┃ ⏎          ┃
┣━━━━━━━━━┻━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┲━━┻━━━━━━━━━━━━┫
┃ lsft       ┃ Z   │ X   │ ?   │ V   │ B   │ :   │ H   │ G   │ ;   │ K   ┃ ent           ┃
┃            ┃   ñ │   ‑ │ -   │   – │   — │ .   │   … │  *µ │ ,   │     ┃ ⇧             ┃
┣━━━━━━━┳━━━━┻━━┳━━┷━━━━┱┴─────┴─────┴─────┴─────┴─────┴─┲━━━┷━━━┳━┷━━━━━╋━━━━━━━┳━━━━━━━┫
┃       ┃       ┃       ┃                                ┃       ┃       ┃       ┃       ┃
┃ Ctrl  ┃ super ┃ Alt   ┃ ␣                              ┃ Alt   ┃ super ┃ menu  ┃ Ctrl  ┃
┗━━━━━━━┻━━━━━━━┻━━━━━━━┹────────────────────────────────┺━━━━━━━┻━━━━━━━┻━━━━━━━┻━━━━━━━┛
'''

# AltGr layer, including standard dead keys
# https://github.com/OneDeadKey/kalamine/blob/main/docs/README.md#standard-dead-keys
# Example: add a grave accent: AltGr + N, Shift + I -> Ì
altgr = '''
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┲━━━━━━━━━━┓
│     │     │     │     │     │     │     │     │     │     │     │     │     ┃          ┃
│     │   ¤ │   « │   » │     │   ° │   ≤ │   ≥ │   × │   ± │   ÷ │     │     ┃          ┃
┢━━━━━┷━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┺━━┯━━━━━━━┩
┃        ┃  *^ │   ≤ │   ≥ │  *¤ │   ‰ │  *˚ │     │   × │  *` │  *´ │     │     │       │
┃        ┃   ^ │   < │   > │   $ │   % │   / │   & │   * │   ` │   ´ │     │     │       │
┣━━━━━━━━┻┱────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┲━━━━┷━━━━━━━┪
┃         ┃  *ˇ │     │     │  *˙ │   ≠ │  */ │   ± │  *¯ │     │  *” │     ┃            ┃
┃         ┃   { │   ( │   ) │   } │   = │   \ │   + │   - │   ' │   " │     ┃            ┃
┣━━━━━━━━━┻━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┲━━┻━━━━━━━━━━━━┫
┃            ┃  *~ │  *, │  *˛ │   – │     │     │   ¦ │  *¸ │   : │  *˘ ┃               ┃
┃            ┃   ~ │   [ │   ] │   _ │   # │   ! │   | │   ; │   : │   ? ┃               ┃
┣━━━━━━━┳━━━━┻━━┳━━┷━━━━┱┴─────┴─────┴─────┴─────┴─────┴─┲━━━┷━━━┳━┷━━━━━╋━━━━━━━┳━━━━━━━┫
┃       ┃       ┃       ┃                                ┃       ┃       ┃       ┃       ┃
┃ Ctrl  ┃ super ┃ Alt   ┃ ␣                              ┃ Alt   ┃ super ┃ menu  ┃ Ctrl  ┃
┗━━━━━━━┻━━━━━━━┻━━━━━━━┹────────────────────────────────┺━━━━━━━┻━━━━━━━┻━━━━━━━┻━━━━━━━┛
'''

# https://github.com/OneDeadKey/kalamine/blob/main/docs/README.md#space-bar
[spacebar]
shift       = "\u00a0"  # NO-BREAK SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u202f"  # NARROW NO-BREAK SPACE
