name        = "Ergo-LR"
name8       = "ergolr"
locale      = "en"
variant     = "ergol"
description = "French (Ergo-LR, 4x6)"
author      = "rdeneau"
url         = "https://github.com/rdeneau/kalamine"
geometry    = "ERGO"
version     = "1.0.0"

# Legend for special keys:
# lmet = Windows (Left)
# lalt = Alt (Left)
# ralt = AltGr (Right)
# ***  = 1st dead key 1dk (Accents Layer)
# &&&  = 2nd dead key 2dk (NavNum Layer) (Omitted, Handled by the keyboard directly)
# ent  = Enter
# spc  = Space
# menu = Property (~ Right Click)
# lctl / rctl = Control (Left / Right)

# F1..F12 are encoded as single characters: Circled Digits/Numbers
# F1 -> ①, F2 -> ②...
# https://www.fileformat.info/info/unicode/block/enclosed_alphanumerics/list.htm

# Base layer, including 1dk
#                +-----+
# shift -------> | ? ¿ | <----- 1dk, shift+key
# base --------> | / ÷ | <----- 1dk, key
#                +-----+
base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ esc ┃ $   │ ' ❝ │ "  ❝│ €  ❞│ %  ‰┃ |  ∅│ &  ≤│ *  ›│ #  ♯│ @  ≈┃ ins ┆     ┆
┆     ┃ ② ¤ │ ③ « │ ④ « │ ⑤ » │ ⑥ ° ┃ ⑦ ÷ │ ⑧ ‹ │ ⑨ ≥ │ ⑩ ± │ ⑪ ÷ ┃ ⑫   ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Q   │ C   │ O   │ P   │ W   ┃ J   │ M   │ D   │ !   │ Y   ┃ del ┆     ┆
·     ┃   â │   ç │   œ │   ô │   § ┃   ↩ │   µ │   • │***  │   û ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ S   │ E   │ N   │ F   ┃ L   │ R   │ T   │ I   │ U   ┃ bspc┆     ┆
·     ┃   à │   è │   é │   ê │   ≠ ┃   ↔ │   → │   î │   ï │   ù ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ lsft┃ Z   │ X   │ ?   │ V   │ B   ┃ :   │ H   │ G   │ ;   │ K   ┃     ·     ·
┆     ┃   ñ │   ⇥ │ - — │   – │   ‑ ┃ . · │   … │  *µ │ ,   │     ┃     ·     ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚
'''

# AltGr layer, including standard dead keys
# https://github.com/OneDeadKey/kalamine/blob/main/docs/README.md#standard-dead-keys
# Example: add a grave accent: AltGr + N, Shift + I -> Ì
altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
┆     ┃ ①   │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *^ │     │     │  *¤ │     ┃  *˚ │     │   × │  *` │  *´ ┃     ┆     ┆
·     ┃   ^ │   < │   > │   $ │   % ┃   / │   & │   * │   ` │   ´ ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃  *ˇ │     │     │  *˙ │   ≠ ┃  */ │   ± │  *¯ │     │  *” ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   = ┃   \ │   + │   - │   ' │   " ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃  *~ │  *, │  *˛ │   – │     ┃     │   ¦ │  *¸ │     │  *˘ ┃     ·     ·
┆     ┃   ~ │   [ │   ] │   _ │   # ┃   ! │   | │   : │   ; │   ? ┃     ·     ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

# https://github.com/OneDeadKey/kalamine/blob/main/docs/README.md#space-bar
[spacebar]
shift       = "\u00a0"  # NO-BREAK SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u202f"  # NARROW NO-BREAK SPACE
